# jetty
server:
    jetty:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    #context-path: /browse-mall

# spring + mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: test
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
        max-file-size: 100MB
        max-request-size: 100MB
        enabled: true
    # 指定静态资源的路径
#    resources:
#        static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
#mybatis:
#    mapperLocations: classpath:api/**/*.xml
#    configLocation: classpath:mybatis.xml
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.hwolf.entity
#  typeEnumsPackage: cn.hwolf.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    # 删除
    logic-delete-value: 1
    # 保留
    logic-not-delete-value: 0
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
debug: true